build:
  nodes:
    coverage:
      environment:
        php:
          version: 8
        variables:
          XDEBUG_MODE: "coverage"
      tests:
        override:
          - command: ./vendor/bin/phpunit --coverage-clover coverage.xml
            coverage:
              file: coverage.xml
              format: clover